package org.restlesscode.listeners;

import org.restlesscode.MessageContext;
import org.restlesscode.MessageListenerAdapter;
import org.springframework.jdbc.BadSqlGrammarException;

import java.sql.SQLException;

public class ChannelLogger extends MessageListenerAdapter {

    @Override
    public boolean handleMessage(MessageContext messageContext) {
        if (! messageContext.getSender().equals(messageContext.getBotName()) && ! messageContext.getMessage().startsWith("!")) {
            simpleJdbcTemplate.update("INSERT INTO messages (nick, message, classification) VALUES (?, ?, ?)",
                messageContext.getSender().replaceAll("_", ""), messageContext.getMessage(), "neutral");
        }

        return true;
    }

    @Override
    public void doInit() {
        try {
            simpleJdbcTemplate.queryForInt("SELECT COUNT(*) FROM messages");
        } catch (BadSqlGrammarException e) {
            System.out.println("Initializing tables.");
            doFirstInit();
        }
    }

    @Override
    public void doFirstInit() {
        simpleJdbcTemplate.update("CREATE TABLE messages ( id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, " +
                "nick VARCHAR(50), message CLOB, classification VARCHAR(20) )");
    }
}
